import type { CSSProperties } from "react";

export const C = {
  bgPage: "#101024",
  bgDark: "#1A1A2E",
  bgCard: "#16213E",
  bgHeader: "#0F3460",
  accent: "#E8FF47",
  white: "#FFFFFF",
  lightGray: "#B0B0C0",
  midGray: "#6B6B80",
  faint: "#5A5A78",
  line: "#202040",
  red: "#FF4757",
  green: "#2ED573",
};

export const DISPLAY = "'Space Grotesk', -apple-system, BlinkMacSystemFont, sans-serif";
export const BODY = "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
export const EASE = "cubic-bezier(.2,.8,.2,1)";

export const styles: Record<string, CSSProperties> = {
  page: { minHeight: "100vh", background: C.bgPage, display: "flex", justifyContent: "center", fontFamily: BODY },
  container: { width: "100%", maxWidth: 440, minHeight: "100vh", background: C.bgDark, color: C.white, position: "relative", overflow: "hidden", paddingBottom: 48 },
  accentBar: { height: 5, background: C.accent },
  homeHeader: { textAlign: "center", padding: "44px 24px 30px", position: "relative" },
  logoTitle: { fontFamily: DISPLAY, fontSize: 38, fontWeight: 700, letterSpacing: -0.5, color: C.accent, margin: 0, lineHeight: 1 },
  logoSub: { color: C.lightGray, fontSize: 13, margin: "10px 0 0", letterSpacing: 0.2 },
  signOutBtn: { position: "absolute", top: 20, right: 20, background: "transparent", border: "1px solid #33334D", color: C.midGray, borderRadius: 8, padding: "6px 12px", fontSize: 11, fontWeight: 600, cursor: "pointer" },
  weekCard: { margin: "0 24px 26px", background: C.bgCard, border: `1px solid ${C.bgHeader}`, borderRadius: 18, padding: "22px 20px 20px" },
  weekDotsRow: { display: "flex", gap: 10, justifyContent: "center" },
  weekDot: { flex: 1, height: 44, borderRadius: 13, display: "flex", alignItems: "center", justifyContent: "center", transition: `background .4s ${EASE}` },
  weekDotText: { fontFamily: DISPLAY, fontSize: 15, fontWeight: 700 },
  weekInfo: { textAlign: "center", marginTop: 18, display: "flex", flexDirection: "column", gap: 4 },
  weekPhase: { fontSize: 14, fontWeight: 700, letterSpacing: 0.2 },
  weekDesc: { fontSize: 11.5, color: C.midGray },
  homeCards: { padding: "0 24px", display: "flex", flexDirection: "column", gap: 16 },
  workoutCard: { display: "flex", alignItems: "center", gap: 18, width: "100%", background: C.bgCard, border: `1px solid ${C.bgHeader}`, borderRadius: 18, padding: "22px 20px", textAlign: "left", color: C.white, cursor: "pointer" },
  cardEmoji: { fontSize: 34, lineHeight: 1 },
  cardBody: { flex: 1, display: "flex", flexDirection: "column", gap: 5 },
  cardTitleRow: { display: "flex", alignItems: "center", gap: 9 },
  cardTitle: { fontFamily: DISPLAY, fontSize: 19, fontWeight: 700 },
  todayTag: { fontSize: 9.5, fontWeight: 700, letterSpacing: 1.2, background: C.accent, color: C.bgDark, padding: "3px 8px", borderRadius: 6 },
  cardSub: { fontSize: 13, color: C.lightGray },
  cardCount: { fontSize: 11, color: C.midGray, letterSpacing: 0.3 },
  playIcon: { fontSize: 17, color: C.accent },
  historyBtn: { display: "block", margin: "30px auto 0", background: "transparent", border: "1px solid #33334D", color: C.lightGray, borderRadius: 12, padding: "14px 30px", fontSize: 13.5, fontWeight: 600, cursor: "pointer" },
  workoutNav: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 20px", borderBottom: `1px solid ${C.bgHeader}` },
  workoutNavLeft: { display: "flex", alignItems: "center", gap: 10 },
  workoutNavTitle: { fontFamily: DISPLAY, fontSize: 15, fontWeight: 700 },
  weekBadge: { fontSize: 10, fontWeight: 700, letterSpacing: 0.6, color: C.bgDark, padding: "3px 8px", borderRadius: 6 },
  exitBtn: { background: "transparent", border: "1px solid #4A2233", color: C.red, borderRadius: 9, padding: "8px 15px", fontSize: 12, fontWeight: 600, cursor: "pointer" },
  currentCard: { margin: "22px 18px 0", background: C.bgCard, border: `1px solid ${C.bgHeader}`, borderRadius: 22, padding: "28px 22px 26px", textAlign: "center" },
  currentLabel: { fontSize: 9.5, fontWeight: 700, letterSpacing: 2.4, color: C.accent, marginBottom: 12 },
  currentName: { fontFamily: DISPLAY, fontSize: 25, fontWeight: 700, lineHeight: 1.18, letterSpacing: -0.3, margin: 0 },
  currentReps: { fontSize: 14, color: C.lightGray, marginBottom: 8 },
  lastKgHint: { fontSize: 11.5, color: C.midGray, marginBottom: 4 },
  setsRow: { display: "flex", justifyContent: "center", gap: 8, margin: "16px 0 24px" },
  setDot: { width: 40, height: 40, borderRadius: 11, display: "flex", alignItems: "center", justifyContent: "center", border: "2px solid transparent", transition: "all .2s" },
  setDotText: { fontSize: 13, fontWeight: 700 },
  okBtn: { width: "100%", padding: 17, background: C.accent, color: C.bgDark, border: "none", borderRadius: 15, fontFamily: DISPLAY, fontSize: 15, fontWeight: 700, letterSpacing: 0.8, cursor: "pointer" },
  inputLabel: { fontSize: 13, color: C.lightGray, fontWeight: 600, display: "block", marginBottom: 10 },
  inputRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 12, marginBottom: 14 },
  kgAdjBtn: { width: 48, height: 48, borderRadius: 12, background: C.bgHeader, color: C.accent, border: "none", fontSize: 22, fontWeight: 700, cursor: "pointer" },
  kgInput: { width: 90, height: 48, borderRadius: 12, border: "2px solid " + C.accent, background: C.bgDark, color: C.accent, fontSize: 24, fontWeight: 800, textAlign: "center", outline: "none" },
  unitHint: { fontSize: 11, color: C.midGray, textAlign: "center", marginBottom: 14, letterSpacing: 0.3 },
  confirmBtn: { width: "100%", padding: 17, background: C.green, color: "#0E2A1A", border: "none", borderRadius: 15, fontFamily: DISPLAY, fontSize: 15, fontWeight: 700, letterSpacing: 0.8, cursor: "pointer" },
  restWrap: { display: "flex", flexDirection: "column", alignItems: "center" },
  restLabel: { fontSize: 9.5, fontWeight: 700, letterSpacing: 2.4, color: C.midGray, marginBottom: 14 },
  ringWrap: { position: "relative", width: 168, height: 168 },
  ringCenter: { position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" },
  restTimer: { fontFamily: DISPLAY, fontSize: 52, fontWeight: 700, color: C.accent, lineHeight: 1, fontVariantNumeric: "tabular-nums" },
  restUnit: { fontSize: 11, color: C.midGray, letterSpacing: 1.6, marginTop: 4 },
  nextUp: { fontSize: 12, color: C.midGray, marginTop: 16 },
  skipBtn: { marginTop: 16, background: "transparent", border: "1px solid #33334D", color: C.lightGray, borderRadius: 12, padding: "12px 30px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  upcomingSection: { margin: "28px 18px 0" },
  upcomingHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 6px", marginBottom: 6 },
  upcomingLabel: { fontSize: 9.5, fontWeight: 700, letterSpacing: 2.4, color: C.midGray },
  upcomingCount: { fontSize: 9.5, fontWeight: 700, letterSpacing: 1.4, color: C.midGray },
  upcomingList: { maxHeight: 196, overflowY: "auto", maskImage: "linear-gradient(#000 78%, transparent)", WebkitMaskImage: "linear-gradient(#000 78%, transparent)" } as CSSProperties,
  upcomingItem: { display: "flex", alignItems: "center", gap: 14, padding: "15px 6px", borderBottom: `1px solid ${C.line}`, transition: "opacity .4s" },
  upcomingNum: { width: 26, flexShrink: 0, fontFamily: DISPLAY, fontSize: 12, fontWeight: 700, color: C.faint, fontVariantNumeric: "tabular-nums" },
  upcomingInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 3, minWidth: 0 },
  upcomingName: { fontSize: 14, fontWeight: 600 },
  upcomingMeta: { fontSize: 11, color: C.midGray },
  upcomingPlay: { width: 34, height: 34, borderRadius: 11, background: C.bgCard, border: `1px solid ${C.bgHeader}`, color: C.accent, fontSize: 12, cursor: "pointer", flexShrink: 0 },
  topNav: { padding: "18px 20px", borderBottom: `1px solid ${C.bgHeader}` },
  backBtn: { background: "transparent", border: "none", color: C.accent, fontSize: 14.5, fontWeight: 600, cursor: "pointer", padding: 0 },
  histBody: { padding: "26px 20px 0" },
  histTitle: { fontFamily: DISPLAY, fontSize: 24, fontWeight: 700, letterSpacing: -0.3, margin: "0 0 22px" },
  emptyState: { textAlign: "center", padding: "60px 20px", color: C.midGray, fontSize: 13.5, lineHeight: 1.6 },
  groupHeader: { display: "flex", alignItems: "center", gap: 9, marginBottom: 16 },
  groupName: { fontFamily: DISPLAY, fontSize: 16, fontWeight: 700, color: C.accent },
  groupRule: { flex: 1, height: 1, background: C.line },
  groupCount: { fontSize: 10.5, color: C.midGray, letterSpacing: 0.8 },
  histEntry: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", background: "transparent", border: "none", borderBottom: `1px solid ${C.line}`, padding: "15px 4px", color: C.white, fontSize: 13.5, cursor: "pointer", textAlign: "left" },
  histEntryLeft: { display: "flex", alignItems: "baseline", gap: 8 },
  histEntryDate: { fontFamily: DISPLAY, fontWeight: 700 },
  histEntryWeek: { fontSize: 10.5, color: C.midGray },
  histEntryCount: { fontSize: 12, color: C.midGray },
  detailTitle: { fontFamily: DISPLAY, fontSize: 21, fontWeight: 700, margin: "0 0 4px" },
  detailSub: { fontSize: 12, color: C.midGray, margin: "0 0 22px" },
  histExCard: { background: C.bgCard, border: `1px solid ${C.bgHeader}`, borderRadius: 14, padding: "15px 16px", marginBottom: 10 },
  histExName: { fontSize: 13.5, fontWeight: 600, marginBottom: 11 },
  histSetsRow: { display: "flex", gap: 9, flexWrap: "wrap" },
  histSetBadge: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2, background: C.bgHeader, borderRadius: 10, padding: "8px 13px", minWidth: 54 },
  histSetLabel: { fontSize: 9.5, color: C.midGray, fontWeight: 700, letterSpacing: 0.6 },
  histSetKg: { fontFamily: DISPLAY, fontSize: 16, fontWeight: 700, color: C.accent },
  doneWrap: { minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "0 28px", textAlign: "center" },
  doneBadgeWrap: { position: "relative", width: 96, height: 96, display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 26 },
  doneGlow: { position: "absolute", inset: 0, borderRadius: "50%", background: C.green, opacity: 0.14, animation: "tabGlowPulse 3s ease-in-out infinite" },
  doneCheck: { width: 76, height: 76, borderRadius: "50%", background: C.bgCard, border: `1.5px solid ${C.green}`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 34, color: C.green, animation: `tabPopIn .6s ${EASE} both` },
  doneTitle: { fontFamily: DISPLAY, fontSize: 29, fontWeight: 700, letterSpacing: -0.4, margin: 0 },
  doneSub: { color: C.midGray, fontSize: 13, margin: "10px 0 32px" },
  doneStats: { display: "flex", gap: 10, width: "100%", marginBottom: 36 },
  doneStat: { flex: 1, background: C.bgCard, border: `1px solid ${C.bgHeader}`, borderRadius: 16, padding: "18px 8px", display: "flex", flexDirection: "column", gap: 5 },
  doneStatValue: { fontFamily: DISPLAY, fontSize: 26, fontWeight: 700, color: C.accent, lineHeight: 1, fontVariantNumeric: "tabular-nums" },
  doneStatLabel: { fontSize: 9.5, color: C.midGray, letterSpacing: 1.2, fontWeight: 700 },
  doneBtn: { background: C.accent, color: C.bgDark, border: "none", borderRadius: 15, padding: "17px 42px", fontFamily: DISPLAY, fontSize: 15, fontWeight: 700, letterSpacing: 0.5, cursor: "pointer", boxShadow: "0 10px 30px -16px rgba(232,255,71,.9)" },
  loadingWrap: { minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", color: C.midGray, fontSize: 13 },
};
